version: '3.9'
services:
  adguard-home:
    image: adguard/adguardhome
    container_name: adguard-home
    ports:
      - 53:53/tcp     # dns
      - 53:53/udp     # dns
      - 8000:80       # http
      - 8001:443/tcp  # dns-over-https
      - 8001:443/udp  # dns-over-https
      - 8002:3000     # web
    volumes:
      - /opt/docker-compose/adguardhome/work:/opt/adguardhome/work
      - /opt/docker-compose/adguardhome/conf:/opt/adguardhome/conf
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}"
    restart: unless-stopped

  unifi:
    image: linuxserver/unifi-controller
    container_name: unifi
    environment:
      PUID: ${DEFAULT_USER}
      PGID: ${DEFAULT_GROUP}
    volumes:
      - /opt/docker-compose/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 6789:6789
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}"
    restart: unless-stopped

  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9001:9001
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}"
    restart: unless-stopped

  qbittorrent-dlc:
    image: hotio/qbittorrent:release-4.3.8.99-202110081405-7423-ac5c264e6
    container_name: qbittorrent-dlc
    environment:
      TZ: ${TIMEZONE}
      PUID: ${DEFAULT_USER}
      PGID: ${DEFAULT_GROUP}
      WEBUI_PORTS: 8081
    ports:
      - 47882:47882/tcp
      - 47882:47882/udp
      - 8081:8081
    volumes:
      - /opt/docker-compose/qbittorrent-dlc:/config
      - /server-storage:/data
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}"
    restart: unless-stopped