radarr:
  radarr_main:
    base_url: http://radarr:7878
    api_key: !secret radarr_apikey
    delete_old_custom_formats: true
    replace_existing_custom_formats: false
    custom_formats:
      - trash_ids:
          - 570bc9ebecd92723d2d21500f4be314c # Movie Versions Remaster
          - eca37840c13c6ef2dd0262b141a5482f # Movie Versions 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Movie Versions Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Movie Versions Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Movie Versions Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Movie Versions Special Edition
          - eecf3a857724171f968a66cb5719e152 # Movie Versions IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # Movie Versions IMAX Enhanced
          - ed27ebfef2f323e964fb1f61391bcb35 # HQ Release Groups HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HQ Release Groups HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HQ Release Groups HD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # HQ Release Groups Web Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # HQ Release Groups Web Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # HQ Release Groups Web Tier 03
          - e7718d7a3ce595f289bfee26adc178f5 # Misc Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Misc Repack2
          - ed38b889b31be83fda192888e2286d83 # Unwanted BR-DISK
          - 90a6f9a284dff5103f6346090e6280c8 # Unwanted LQ
          - e204b80c87be9497a8a6eaff48f72905 # Unwanted LQ (Release Title)
          - dc98083864ea246d05a42df0d05f81cc # Unwanted x265 (HD)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # Unwanted 3D
          - 0a3f082873eb454bde444150b70253cc # Unwanted Extras
          - b6832f586342ef70d9c128d40c07b872 # Optional Unwanted Bad Dual Groups
          - 90cedc1fea7ea5d11298bebd3d1d3223 # Optional Unwanted EVO (no WEBDL)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # Optional Unwanted No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Optional Unwanted Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Optional Unwanted Retags
          - f537cf427b64c38c8e36298f657e4828 # Optional Unwanted Scene
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # Streaming Services AMZN
          - 40e9380490e748672c2522eaaeb692f7 # Streaming Services ATVP
          - cc5e51a9e85a6296ceefe097a77f12f4 # Streaming Services BCORE
          - f6ff65b3f4b464a79dcc75950fe20382 # Streaming Services CRAV
          - 16622a6911d1ab5d5b8b713d5b0036d4 # Streaming Services CRiT
          - 84272245b2988854bfb76a16e60baea5 # Streaming Services DSNP
          - 917d1f2c845b2b466036b0cc2d7c72a3 # Streaming Services FOD
          - 509e5f41146e278f9eab1ddaceb34515 # Streaming Services HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad # Streaming Services HMAX
          - 526d445d4c16214309f0fd2b3be18a89 # Streaming Services Hulu
          - 6185878161f1e2eef9cd0641a0d09eae # Streaming Services IP
          - 2a6039655313bf5dab1e43523b62c374 # Streaming Services MA
          - 6a061313d22e51e0f25b7cd4dc065233 # Streaming Services MAX
          - 170b1d363bd8516fbf3a3eb05d4faff6 # Streaming Services NF
          - fbca986396c5e695ef7b2def3c755d01 # Streaming Services OViD
          - bf7e73dd1d85b12cc527dc619761c840 # Streaming Services Pathe
          - c9fd353f8f5f1baf56dc601c4cb29920 # Streaming Services PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd # Streaming Services PMTP
          - c2863d2a50c9acad1fb50e53ece60817 # Streaming Services STAN
          - f1b0bae9bc222dab32c1b38b5a7a1088 # Streaming Services TVer
          - 279bda7434fd9075786de274e6c3c202 # Streaming Services U-NEXT
        assign_scores_to:
          - name: Default
    quality_definition:
      type: movie
    quality_profiles:
      - name: Default
        reset_unmatched_scores:
          enabled: true
          except:
            - "Language: Not Original"
        score_set: default
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
          until_score: 1800
        min_format_score: 0
        qualities:
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: HDTV-720p
          - name: Bluray-576p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p

sonarr:
  sonarr_main:
    base_url: http://sonarr:8989
    api_key: !secret sonarr_apikey
    delete_old_custom_formats: true
    replace_existing_custom_formats: false
    custom_formats:
      - trash_ids:
          - 85c61753df5da1fb2aab6f2a47426b09 # Unwanted BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # Unwanted LQ
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # Unwanted LQ (Release Title)
          - 47435ece6b99a0b477caf360e79ba0bb # Unwanted x265 (HD)
          - fbcb31d8dabd2a319072b84fc0b7249c # Unwanted Extras
          - 32b367365729d530ca1c124a0b180c64 # Optional Unwanted Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # Optional Unwanted No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Optional Unwanted Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Optional Unwanted Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Optional Unwanted Scene
          - ec8fa7296b64e8cd390a1600981f3923 # Misc Repack/Proper
          - eb3d5cc0a2be0db205fb823640db6a3c # Misc Repack v2
          - 44e7c4de10ae50265753082e5dc76047 # Misc Repack v3
          - bbcaf03147de0f73be2be4a9078dfa03 # Streaming Services 4OD
          - fcc09418f67ccaddcf3b641a22c5cfd7 # Streaming Services ALL4
          - d660701077794679fd59e8bdf4ce3a29 # Streaming Services AMZN
          - f67c9ca88f463a48346062e8ad07713f # Streaming Services ATVP
          - 77a7b25585c18af08f60b1547bb9b4fb # Streaming Services CC
          - 4e9a630db98d5391aec1368a0256e2fe # Streaming Services CRAV
          - 36b72f59f4ea20aad9316f475f2d9fbb # Streaming Services DCU
          - 89358767a60cc28783cdc3d0be9388a4 # Streaming Services DSNP
          - 7be9c0572d8cd4f81785dacf7e85985e # Streaming Services FOD
          - 7a235133c87f7da4c8cccceca7e3c7a6 # Streaming Services HBO
          - a880d6abc21e7c16884f3ae393f84179 # Streaming Services HMAX
          - f6cce30f1733d5c8194222a7507909bb # Streaming Services HULU
          - dc503e2425126fa1d0a9ad6168c83b3f # Streaming Services IP
          - 0ac24a2a68a9700bcb7eeca8e5cd644c # Streaming Services iT
          - 81d1fbf600e2540cee87f3a23f9d3c1c # Streaming Services MAX
          - d34870697c9db575f17700212167be23 # Streaming Services NF
          - b2b980877494b560443631eb1f473867 # Streaming Services NLZ
          - fb1a91cdc0f26f7ca0696e0e95274645 # Streaming Services OViD
          - 1656adc6d7bb2c8cca6acfb6592db421 # Streaming Services PCOK
          - c67a75ae4a1715f2bb4d492755ba4195 # Streaming Services PMTP
          - 3ac5d84fce98bab1b531393e9c82f467 # Streaming Services QIBI
          - c30d2958827d1867c73318a5a2957eb1 # Streaming Services RED
          - ae58039e1319178e6be73caab5c42166 # Streaming Services SHO
          - 1efe8da11bfd74fbbcd4d8117ddb9213 # Streaming Services STAN
          - d100ea972d1af2150b65b1cffb80f6b5 # Streaming Services TVer
          - 0e99e7cc719a8a73b2668c3a0c3fe10c # Streaming Services U-NEXT
          - 5d2317d99af813b6529c7ebf01c83533 # Streaming Services VDL
          - e6258996055b9fbab7e9cb2f75819294 # HQ Source Groups WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # HQ Source Groups WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6 # HQ Source Groups WEB Tier 03
          - d0c516558625b04b363fa6c5c2c7cfd4 # HQ Source Groups WEB Scene
        assign_scores_to:
          - name: Default
    quality_definition:
      type: series
    quality_profiles:
      - name: Default
        reset_unmatched_scores:
          enabled: true
          except:
            - "Language: Not Original"
        score_set: default
        upgrade:
          allowed: true
          until_quality: WEB 1080p
          until_score: 1800
        min_format_score: 0
        qualities:
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: HDTV-720p
          - name: DVD
            qualities:
              - Bluray-480p
              - DVD
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
          - name: SDTV

  sonarr_anime:
    base_url: http://sonarr-anime:8989
    api_key: !secret sonarr_anime_apikey
    delete_old_custom_formats: true
    replace_existing_custom_formats: false
    custom_formats:
      - trash_ids:
          - 949c16fe0a8147f50ba82cc2df9411c9 # Anime BD Tier 01 (Top SeaDex Muxers)
          - ed7f1e315e000aef424a58517fa48727 # Anime BD Tier 02 (SeaDex Muxers)
          - 096e406c92baa713da4a72d88030b815 # Anime BD Tier 03 (SeaDex Muxers)
          - 30feba9da3030c5ed1e0f7d610bcadc4 # Anime BD Tier 04 (SeaDex Muxers)
          - 545a76b14ddc349b8b185a6344e28b04 # Anime BD Tier 05 (Remuxes)
          - 25d2afecab632b1582eaf03b63055f72 # Anime BD Tier 06 (FanSubs)
          - 0329044e3d9137b08502a9f84a7e58db # Anime BD Tier 07 (P2P/Scene)
          - c81bbfb47fed3d5a3ad027d077f889de # Anime BD Tier 08 (Mini Encodes)
          - e0014372773c8f0e1bef8824f00c7dc4 # Anime Web Tier 01 (Muxers)
          - 19180499de5ef2b84b6ec59aae444696 # Anime Web Tier 02 (Top FanSubs)
          - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
          - c27f2ae6a4e82373b0f1da094e2489ad # Anime Web Tier 03 (Official Subs)
          - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03
          - 9965a052eb87b0d10313b1cea89eb451 # Remux Tier 01
          - 8a1d0c3d7497e741736761a1da866a2e # Remux Tier 02
          - 4fd5528a3a8024e6b49f9c67053ea5f3 # Anime Web Tier 04 (Official Subs)
          - 29c2a13d091144f63307e4a8ce963a39 # Anime Web Tier 05 (FanSubs)
          - dc262f88d74c651b12e9d90b39f6c753 # Anime Web Tier 06 (FanSubs)
          - 273bd326df95955e1b6c26527d1df89b # v1
          - 228b8ee9aa0a609463efca874524a6b8 # v2
          - 0e5833d3af2cc5fa96a0c29cd4477feb # v3
          - 4fc15eeb8f2f9a749f918217d4234ad8 # v4
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
          - b4a1b3d705159cdca36d71e57ca86871 # Unwanted Anime Raws
          - e3515e519f3b1360cbfc17651944354c # Unwanted Anime LQ Groups
          - 15a05bc7c1a36e2b57fd628f8977e2fc # Unwanted AV1
          - d2d7b8a9d39413da5f44054080e028a3 # Unwanted v0
          - 9c14d194486c4014d422adc64092d794 # UnwantedDubs Only
          - 07a32f77690263bb9fda1842db7e273f # Unwanted VOSTFR
        assign_scores_to:
          - name: default-anime
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        assign_scores_to:
          - name: default-anime
            score: 101
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: default-anime
            score: -1000
    quality_definition:
      type: anime
    quality_profiles:
      - name: default-anime
        reset_unmatched_scores:
          enabled: true
          except:
            - "Language: Not Original"
        score_set: default
        upgrade:
          allowed: true
          until_quality: WEB 1080p
          until_score: 10000
        min_format_score: 100
        qualities:
          - name: Bluray-1080p
            qualities:
              - Bluray-1080p Remux
              - Bluray-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
              - HDTV-1080p
          - name: Bluray-720p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
              - HDTV-720p
          - name: Bluray-480p
          - name: WEB 480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
          - name: DVD
          - name: SDTV
