version: '3.8'
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8001:80/tcp"
    environment:
      TZ: 'Pacific/Auckland'
      WEBPASSWORD: '${PIHOLE_PASSWORD}'
    volumes:
      - /opt/docker-compose/pihole/etc:/etc/pihole/
      - /opt/docker-compose/pihole/dnsmasq.d:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 8.8.8.8
    restart: unless-stopped

  unifi:
    image: linuxserver/unifi-controller
    container_name: unifi
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/docker-compose/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 6789:6789
    restart: unless-stopped
