version: '3.9'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker-compose/admin/portainer:/data
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    env_file:
      - .env
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}"
    restart: unless-stopped

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    env_file:
      - .env
    environment:
      PUID: ${DEFAULT_USER}
      PGID: ${DEFAULT_GROUP}
      APP_URL: ${BOOKSTACK_URL}
      DB_HOST: bookstack_db
      DB_USER: ${BOOKSTACK_DB_USER}
      DB_PASS: ${BOOKSTACK_DB_PASS}
      DB_DATABASE: ${BOOKSTACK_DB_DATABASE}
    volumes:
      - /opt/docker-compose/admin/bookstack:/config
    ports:
      - 7000:80
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}"
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      PUID: ${DEFAULT_USER}
      PGID: ${DEFAULT_GROUP}
      MYSQL_ROOT_PASSWORD: ${BOOKSTACK_DB_PASS}
      TZ: ${TIMEZONE}
      MYSQL_DATABASE: ${BOOKSTACK_DB_DATABASE}
      MYSQL_USER: ${BOOKSTACK_DB_USER}
      MYSQL_PASSWORD: ${BOOKSTACK_DB_PASS}
    volumes:
      - /opt/docker-compose/admin/bookstack-db:/config
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}"
    restart: unless-stopped
    
  homer:
    image: b4bz/homer:latest
    container_name: homer
    environment:
      PUID: ${DEFAULT_USER}
      PGID: ${DEFAULT_GROUP}
    volumes:
      - /opt/docker-compose/admin/homer/assets:/www/assets
    ports:
      - 7100:8080
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}"
    restart: unless-stopped