version: '3.9'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /opt/docker-compose/reverse-proxy/nginx-docker/etc/nginx:/etc/nginx
      - /opt/docker-compose/reverse-proxy/nginx-docker/etc/ssl:/etc/ssl
      - /opt/docker-compose/reverse-proxy/nginx-docker/etc/nginx-index:/opt/index
      - /opt/docker-compose/reverse-proxy/nginx-docker/etc/nginx-access:/etc/apache2
      - /opt/letsencrypt/etc/letsencrypt:/letsencrypt
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 87:80
      - 447:443
    restart: unless-stopped

  cloudflare-ddns:
    image: oznu/cloudflare-ddns
    container_name: cloudflare-ddns
    environment:
      TZ: ${TIMEZONE}
      PROXIED: 'true'
      API_KEY: ${CLOUDFLARE_APIKEY}
      ZONE: ${CLOUDFLARE_DOMAIN}
      SUBDOMAIN: ${CLOUDFLARE_SUBDOMAIN}
    restart: unless-stopped

  # authelia:
  #   image: authelia/authelia:4.32.2
  #   container_name: authelia
  #   environment:
  #     TZ: ${TIMEZONE}
  #   volumes:
  #     - /opt/docker-compose/reverse-proxy/authelia:/config
  #   ports:
  #     - 9091:9091
  #   restart: unless-stopped

  rclone-serve-webdav:
    image: rclone/rclone
    container_name: rclone-serve-webdav
    volumes:
      - /root/.config/rclone/:/root/.config/rclone/:ro
      - /opt/docker-compose/reverse-proxy/rclone-serve-webdav:/opt
      - /gmediac:/gmediac:ro
    command:
      - "serve"
      - "webdav"
      - "/gmediac"
      - "--config"
      - "/root/.config/rclone/rclone.conf"
      - "--verbose"
      - "--buffer-size"
      - "64M"
      - "--no-modtime"
      - "--vfs-read-chunk-size"
      - "64M"
      - "--vfs-read-chunk-size-limit"
      - "1024M"
      - "--dir-cache-time"
      - "900h"
      - "--umask"
      - "002"
      - "--addr"
      - "0.0.0.0:8087"
      - "--read-only"
      - "--include-from"
      - "/opt/include-from.txt"
      - "--template"
      - "/opt/index.html"
    restart: unless-stopped

  librespeed:
    image: adolfintel/speedtest
    container_name: librespeed
    environment:
      IPINFO_APIKEY: ${IPINFO_APIKEY}
      MODE: standalone
      TITLE: ${LIBRESPEED_TITLE}
      WEBPORT: 86
    ports:
      - 86:86
    env_file:
      - .env
    restart: unless-stopped